### ISSUE TITLE
running sudo pihole5-list-tool gives an error

### ISSUE THREAD

**Issue by lukeeexd** [jessedp/pihole5-list-tool#25]
Forms suck. But they can help a ton. Going free-form below is okay if you're certain you're providing all of the relevant information (or things aren't applicable)

## Environment
Describe the system on which this issue occurred: ubuntu 20.04

**pihole5-list-tool** _(ex: 0.4.2, `pip3 show pihole5-list-tool`)_ **:0.5.0**

**OS** _(ex: Ubuntu 20.20, `lsb_release -a`)_ **:Ubuntu 20.04**

**Python** _(ex: 3.8.2, `python --version`)_ **:3.8.2**

**Using Docker?** Y/N
.....**version** _(ex: 19.03.10, `docker -v`)_ **:N**

## Issue Details
When I run sudo pihole5-list-tool it throws an error.

**Expected behavior**
To give the install screen. I've used this on 2 other devices and it's worked fine

**Actual behavior**
`Traceback (most recent call last):
  File "/usr/local/bin/pihole5-list-tool", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ph5lt.py", line 84, in main
    print(color("    \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510", fg="#b61042"))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 21-64: ordinal not in range(256)
`

**Supporting details**
Attach or paste in stack traces, screenshots, and the such...

**Anything else**
Anything else you feel is valuable that wasn't asked for?

**Comment by lukeeexd** [comment]
Ah fixed. I found another issue #4 and followed the instrctions to fix. Appologies
